# Generated by Django 4.2.4 on 2023-09-16 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredients",
            name="slug",
        ),
        migrations.AlterField(
            model_name="tags",
            name="color",
            field=models.CharField(
                max_length=7,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#([0-9a-fA-F]{6}|[0-9a-fA-F]{3})$",
                        message="Поле не содержит цвет в формате HEX",
                    )
                ],
                verbose_name="Цвет тега в HEX",
            ),
        ),
    ]
