# Generated by Django 4.2.4 on 2023-09-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_alter_ingredients_measurement_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredients",
            name="name",
            field=models.TextField(
                max_length=100, verbose_name="Назвение ингридиента"
            ),
        ),
    ]
